### ISSUE TITLE
AnonymousDisposable: unresolved indentifier

### ISSUE THREAD

**Issue by yhyuan** [RxSwiftCommunity/RxCoreData#17]
Hi, 

In NSManagedObjectContext+Rx.swift, the xcode told me that AnonymousDisposable is an unresolved identifier. I am using xcode 8.1 and Swift 3.

**Comment by serluca** [comment]
Hi @yhyuan 

The PR #15 should fix the issue

**Comment by scotteg** [comment]
Resolved
