### ISSUE TITLE
 Pod trunk

### ISSUE THREAD

**Issue by bobgodwinx** [RxSwiftCommunity/RxCoreData#25]
### Required 
- [ ] Pod trunk  the release version `0.4.0`

**Comment by scotteg** [comment]
Hi @ashfurrow, should it be `pod trunk add-owner RxSwiftCommunity/RxCoreData ...` or just `pod trunk add-owner RxCoreData ...`

**Comment by ashfurrow** [comment]
It's just the pod name, which is `RxCoreData`, so the latter should work.

**Comment by scotteg** [comment]
@ashfurrow Got an error: `No owner found with the specified email address.` Should he be added as an owner to RxSwiftCommunity first?

**Comment by scotteg** [comment]
@ashfurrow Got an error: `No owner found with the specified email address.` Should he be added as an owner to RxSwiftCommunity first?

**Comment by ashfurrow** [comment]
Ah, that's not a GitHub thing, that's a CocoaPods problem.

@bobgodwinx have you ever run `pod trunk register` before? If so, please let Scott know what email address is displayed in `pod trunk me`.

**Comment by bobgodwinx** [comment]
@ashfurrow yes I did. you have my email? or you just pin me in private on slack and I will give it to you.

**Comment by scotteg** [comment]
@bobgodwinx Is it the same email as on your GitHub profile?

**Comment by scotteg** [comment]
I received @bobgodwinx's trunk email and have added him as an owner.

**Comment by ashfurrow** [comment]
Awesome, thanks you two!
