### ISSUE TITLE
Lower deployment target 

### ISSUE THREAD

**Issue by vadimb** [RxSwiftCommunity/RxCoreData#5]
Is this necessary to use iOS 9.1 as the minimum deployment target? As far as I know RxSwift and RxCocoa require a minimum dep.  iOS 8.0 .
Can we lower the deployment target to iOS 8 ? I'll be happy to send a PR to do so.

**Comment by scotteg** [comment]
Hi @vadimb, sure, that would be fine. Thanks!

**Comment by serluca** [comment]
@scotteg did you push the podspec? 
I'm receiving this error `Unable to find a specification for "RxCoreData"` that can be related with this issue.

**Comment by scotteg** [comment]
Hi @serluca Yep, I pushed the updated podspec. I just created a new project with RxCoreData and it pulled the correct version (0.2.1). And https://cocoapods.org/?q=rxcoredata also shows the correct version. So, maybe something on your end? Maybe try `pod install` to see if that works?

**Comment by serluca** [comment]
Hi @scotteg 

Ok then is for sure something on my side, it is maybe something with cocoapods cache.
I also have this result: 

```
$ pod search RxCoreData
[!] Unable to find a pod with name, author, summary, or description matching `RxCoreData`
```

**Comment by scotteg** [comment]
@serluca Yep, could be a cache issue. This worked for me:
```
pod search RxCoreData

-> RxCoreData (0.2.1)
   RxSwift extensions for Core Data
   pod 'RxCoreData', '~> 0.2.1'
   - Homepage: https://github.com/RxSwiftCommunity/RxCoreData
   - Source:   https://github.com/RxSwiftCommunity/RxCoreData.git
   - Versions: 0.2.1, 0.2.0, 0.1.0 [master repo]
```

Did you try clearing the cache?

```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by orta** [comment]
You may need to update your repos, try `pod repo update`

**Comment by serluca** [comment]
@orta `pod repo update` didn't work, it worked deleting the cache instead. 
Thank you
