### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by sergdort** [RxSwiftCommunity/RxCoreData#9]
Hi, guys I've already started some changes towards Swift 3.0 support.
If you don't mind I would like to continue working on it :)
So please add `In Progress` label

**Comment by serluca** [comment]
Hi @scotteg 

Any update on the swift 3 support?

**Comment by samscam** [comment]
Between #10 #14 and #16 I'd say this is pretty much closed. @scotteg ??

**Comment by scotteg** [comment]
Resolved
